<#include   "component://workeffortext/config/sql/cardsComparingVersions/common/commonUtils.sql.ftl" />
-- LISTA ALLEGATO MODIFICATE
																												
SELECT  DRN.DATA_RESOURCE_NAME, 
		WTN.DESCRIPTION AS WEC_DESCRITPION, 
		CEN.DESCRIPTION AS C_DESCRIPTION, 
		WCN.FROM_DATE, 
		WCN.THRU_DATE,																								
		WTO.DESCRIPTION AS OLD_WEC_DESCRITPION, 
		CEO.DESCRIPTION AS OLD_C_DESCRIPTION, 
		WCO.FROM_DATE AS OLD_FROM_DATE, 
		WCO.THRU_DATE AS OLD_THRU_DATE	
																	
FROM WORK_EFFORT_CONTENT WCN																						
	INNER JOIN WORK_EFFORT_CONTENT_TYPE WTN ON WTN.WORK_EFFORT_CONTENT_TYPE_ID = WCN.WORK_EFFORT_CONTENT_TYPE_ID
	INNER JOIN CONTENT CEN ON CEN.CONTENT_ID = WCN.CONTENT_ID																					
	INNER JOIN DATA_RESOURCE DRN ON DRN.DATA_RESOURCE_ID = CEN.DATA_RESOURCE_ID																					
	INNER JOIN DATA_RESOURCE DRO ON DRO.DATA_RESOURCE_NAME = DRN.DATA_RESOURCE_NAME																					
	INNER JOIN CONTENT CEO ON CEO.DATA_RESOURCE_ID = DRO.DATA_RESOURCE_ID																					
	INNER JOIN WORK_EFFORT_CONTENT WCO ON WCO.CONTENT_ID = CEO.CONTENT_ID																					
	INNER JOIN WORK_EFFORT_CONTENT_TYPE WTO ON WTO.WORK_EFFORT_CONTENT_TYPE_ID = WCO.WORK_EFFORT_CONTENT_TYPE_ID	
																			
WHERE WCN.WORK_EFFORT_ID = <@param workEffortId/>																							
	AND WCO.WORK_EFFORT_ID = <@param oldWorkEffortId/>																						
	AND (
		<@compareNotEqual "WTN.DESCRIPTION" "WTO.DESCRIPTION" />
		OR <@compareNotEqual "WTN.DESCRIPTION" "WTO.DESCRIPTION" />
		OR WCN.FROM_DATE <> WCO.FROM_DATE 
		OR <@compareNotEqual "WCN.THRU_DATE" "WCO.THRU_DATE" />)																
