SELECT WEP.WORK_EFFORT_NAME AS COLLEGATO, WEA.WORK_EFFORT_NAME AS ASSEGNAZIONE
FROM <@table "WORK_EFFORT_PARTY_ASSIGNMENT"/> WP
INNER JOIN <@table "WORK_EFFORT_PARTY_ASSIGNMENT"/> VALUTATO
ON VALUTATO.ROLE_TYPE_ID = 'WEM_EVAL_IN_CHARGE'
   AND VALUTATO.PARTY_ID = WP.PARTY_ID
INNER JOIN <@table "WORK_EFFORT"/> OBIETTIVO ON OBIETTIVO.WORK_EFFORT_ID = VALUTATO.WORK_EFFORT_ID
INNER JOIN <@table "WORK_EFFORT"/> WEP ON WEP.WORK_EFFORT_ID = WP.WORK_EFFORT_ID
INNER JOIN <@table "WORK_EFFORT_PARTY_ASSIGNMENT"/> WA
ON WA.WORK_EFFORT_ID = WP.WORK_EFFORT_ID_FROM
   AND WA.PARTY_ID = WP.PARTY_ID
   AND WA.ROLE_TYPE_ID = WP.ROLE_TYPE_ID_FROM
   AND WA.FROM_DATE = WP.FROM_DATE_FROM
INNER JOIN <@table "WORK_EFFORT"/> WEA ON WEA.WORK_EFFORT_ID = WA.WORK_EFFORT_ID
WHERE VALUTATO.WORK_EFFORT_ID = <@param workEffortId />
  AND WP.FROM_DATE <= OBIETTIVO.ESTIMATED_COMPLETION_DATE
  AND WP.THRU_DATE >= OBIETTIVO.ESTIMATED_START_DATE
  AND WP.ROLE_TYPE_ID = <@param roleTypeId />
