SELECT
	P.PARTY_NAME,
	P.PARTY_ID,
	PPR.PARENT_ROLE_CODE
FROM
	<@table "PARTY"/> P
INNER JOIN <@table "PARTY_PARENT_ROLE"/> PPR ON
	P.PARTY_ID = PPR.PARTY_ID
WHERE
	P.PARTY_ID IN (
		SELECT
			DISTINCT EC.PARTY_ID
		FROM
			<@table "PARTY_ROLE"/> EC
		INNER JOIN <@table "PARTY_RELATIONSHIP"/> UOEC ON
			UOEC.PARTY_ID_TO = EC.PARTY_ID
			AND UOEC.PARTY_RELATIONSHIP_TYPE_ID = <@param partyRelationshipTypeId />
			AND UOEC.THRU_DATE IS NULL
		INNER JOIN <@table "PARTY_RELATIONSHIP"/> UOEM ON
			UOEM.PARTY_ID_FROM = UOEC.PARTY_ID_FROM
			AND UOEM.ROLE_TYPE_ID_FROM = UOEC.ROLE_TYPE_ID_FROM
			AND UOEM.PARTY_RELATIONSHIP_TYPE_ID IN(
				'ORG_RESPONSIBLE',
				'ORG_DELEGATE'
			)
			AND UOEM.THRU_DATE IS NULL
		INNER JOIN <@table "PARTY_ROLE"/> EM ON
			EM.PARTY_ID = UOEM.PARTY_ID_TO
			AND EM.ROLE_TYPE_ID = 'WEM_EVAL_MANAGER'
		WHERE
			UOEM.PARTY_ID_TO = '${userLogin.partyId}'
	)
ORDER BY P.PARTY_NAME