
  
  SELECT 
  PP.PARENT_ROLE_CODE, PA.PARTY_NAME, PA.PARTY_NAME_LANG, 
  PR.PARTY_ID, PR.ROLE_TYPE_ID

FROM  <@table "PARTY_ROLE"/>  PR 
INNER JOIN  <@table "PARTY"/>  PA ON PA.PARTY_ID = PR.PARTY_ID 
INNER JOIN  <@table "PARTY_PARENT_ROLE"/>  PP ON PP.PARTY_ID = PR.PARTY_ID 
INNER JOIN  <@table "USER_LOGIN"/>  UL ON UL.USER_LOGIN_ID = '${userLogin.userLoginId}'
LEFT OUTER JOIN  <@table "PARTY_RELATIONSHIP"/>  E ON PR.ROLE_TYPE_ID = E.ROLE_TYPE_ID_FROM
        AND PR.PARTY_ID = E.PARTY_ID_FROM
        AND E.PARTY_RELATIONSHIP_TYPE_ID IN ('ORG_RESPONSIBLE', 'ORG_DELEGATE')
        AND E.THRU_DATE IS NULL
        AND E.PARTY_ID_TO = UL.PARTY_ID
LEFT OUTER JOIN  <@table "PARTY_RELATIONSHIP"/>  Z ON PR.ROLE_TYPE_ID = Z.ROLE_TYPE_ID_TO
        AND PR.PARTY_ID = Z.PARTY_ID_TO
        AND Z.PARTY_RELATIONSHIP_TYPE_ID = 'GROUP_ROLLUP'
        AND Z.THRU_DATE IS NULL
LEFT OUTER JOIN  <@table "PARTY_RELATIONSHIP"/>  Y ON Z.ROLE_TYPE_ID_FROM = Y.ROLE_TYPE_ID_FROM
        AND Z.PARTY_ID_FROM = Y.PARTY_ID_FROM
        AND Y.PARTY_RELATIONSHIP_TYPE_ID IN ('ORG_RESPONSIBLE', 'ORG_DELEGATE')
        AND Y.THRU_DATE IS NULL 
        AND Y.PARTY_ID_TO = UL.PARTY_ID
LEFT OUTER  JOIN <@table "PARTY_RELATIONSHIP"/>  Z2 ON Z.ROLE_TYPE_ID_FROM = Z2.ROLE_TYPE_ID_TO
        AND Z.PARTY_ID_FROM = Z2.PARTY_ID_TO
        AND Z2.PARTY_RELATIONSHIP_TYPE_ID = 'GROUP_ROLLUP'
        AND Z2.THRU_DATE IS NULL 
LEFT OUTER JOIN <@table "PARTY_RELATIONSHIP"/>  Y2 ON Z2.ROLE_TYPE_ID_FROM = Y2.ROLE_TYPE_ID_FROM
        AND Z2.PARTY_ID_FROM = Y2.PARTY_ID_FROM
        AND Y2.PARTY_RELATIONSHIP_TYPE_ID IN ('ORG_RESPONSIBLE', 'ORG_DELEGATE')
        AND Y2.THRU_DATE IS NULL 
        AND Y2.PARTY_ID_TO = UL.PARTY_ID
WHERE PR.PARENT_ROLE_TYPE_ID = 'ORGANIZATION_UNIT'
  
  <#if statusId?has_content>
  AND PA.STATUS_ID = <@param statusId />
  </#if>
  
  <#if roleTypeId?has_content>
   AND PR.ROLE_TYPE_ID = <@param roleTypeId />
  </#if> 
  
  <#if organizationId?has_content>
  AND PP.ORGANIZATION_ID = <@param organizationId />
  </#if>  

  AND (1 = 0
  	   <#if isOrgMgr?default(false) == true>
          OR E.PARTY_ID_TO IS NOT NULL
       </#if>
       <#if isSup?default(false) == true>
    	  OR  Y.PARTY_ID_TO IS NOT NULL
       </#if>
       <#if isTop?default(false) == true>
          OR  Y2.PARTY_ID_TO IS NOT NULL
       </#if>       
  )

GROUP BY
  PP.PARENT_ROLE_CODE, PA.PARTY_NAME, PA.PARTY_NAME_LANG, 
  PR.PARTY_ID, PR.ROLE_TYPE_ID
  
 ORDER BY PP.PARENT_ROLE_CODE