SELECT P.WORK_EFFORT_ID AS PROJECT_ID, P.WORK_EFFORT_NAME AS PROJECT_NAME, T.WORK_EFFORT_ID AS TASK_ID, T.WORK_EFFORT_NAME AS TASK_NAME,
<#if showParty?if_exists?has_content && "Y" == showParty>
	A.PARTY_ID, PP.PARTY_NAME,
</#if> 
T.ESTIMATED_START_DATE, T.ESTIMATED_COMPLETION_DATE,
SUM(A.HOURS) AS HOURS 
FROM <@table "TIME_ENTRY"/> A
INNER JOIN <@table "PARTY"/> PP ON PP.PARTY_ID = A.PARTY_ID  
INNER JOIN <@table "WORK_EFFORT"/> T ON T.WORK_EFFORT_ID = A.WORK_EFFORT_ID                
INNER JOIN <@table "WORK_EFFORT"/> F ON F.WORK_EFFORT_ID = T.WORK_EFFORT_PARENT_ID
INNER JOIN <@table "WORK_EFFORT"/> P ON P.WORK_EFFORT_ID = F.WORK_EFFORT_PARENT_ID
INNER JOIN <@table "WORK_EFFORT_ASSOC"/> S ON S.WORK_EFFORT_ID_TO = T.WORK_EFFORT_ID AND T.WORK_EFFORT_TYPE_ID = 'TASK'
INNER JOIN <@table "WORK_EFFORT"/> W ON W.WORK_EFFORT_ID = S.WORK_EFFORT_ID_FROM
WHERE W.WORK_EFFORT_ID = <@param workEffortId /> AND A.FROM_DATE >= W.ESTIMATED_START_DATE AND A.FROM_DATE <= W.ESTIMATED_COMPLETION_DATE

GROUP BY P.WORK_EFFORT_ID, P.WORK_EFFORT_NAME, T.WORK_EFFORT_ID, T.WORK_EFFORT_NAME,
<#if showParty?if_exists?has_content && "Y" == showParty>
	A.PARTY_ID, PP.PARTY_NAME,
</#if> 
T.ESTIMATED_START_DATE, T.ESTIMATED_COMPLETION_DATE

UNION ALL

SELECT P.WORK_EFFORT_ID AS PROJECT_ID, P.WORK_EFFORT_NAME AS PROJECT_NAME, T.WORK_EFFORT_ID AS TASK_ID, T.WORK_EFFORT_NAME AS TASK_NAME,
<#if showParty?if_exists?has_content && "Y" == showParty>
	A.PARTY_ID, PP.PARTY_NAME,
</#if> 
T.ESTIMATED_START_DATE, T.ESTIMATED_COMPLETION_DATE,
SUM(A.HOURS) AS HOURS 
FROM <@table "TIME_ENTRY"/> A
INNER JOIN <@table "PARTY"/> PP ON PP.PARTY_ID = A.PARTY_ID  
INNER JOIN <@table "WORK_EFFORT"/> T ON T.WORK_EFFORT_ID = A.WORK_EFFORT_ID
INNER JOIN <@table "WORK_EFFORT"/> F ON F.WORK_EFFORT_ID = T.WORK_EFFORT_PARENT_ID
INNER JOIN <@table "WORK_EFFORT"/> P ON P.WORK_EFFORT_ID = F.WORK_EFFORT_PARENT_ID
INNER JOIN <@table "WORK_EFFORT_ASSOC"/> S ON S.WORK_EFFORT_ID_TO = F.WORK_EFFORT_ID AND F.WORK_EFFORT_TYPE_ID = 'PHASE'
INNER JOIN <@table "WORK_EFFORT"/> W ON W.WORK_EFFORT_ID = S.WORK_EFFORT_ID_FROM
WHERE W.WORK_EFFORT_ID = <@param workEffortId /> AND A.FROM_DATE >= W.ESTIMATED_START_DATE AND A.FROM_DATE <= W.ESTIMATED_COMPLETION_DATE

GROUP BY P.WORK_EFFORT_ID, P.WORK_EFFORT_NAME, T.WORK_EFFORT_ID, T.WORK_EFFORT_NAME,
<#if showParty?if_exists?has_content && "Y" == showParty>
	A.PARTY_ID, PP.PARTY_NAME,
</#if> 
T.ESTIMATED_START_DATE, T.ESTIMATED_COMPLETION_DATE

UNION ALL

SELECT P.WORK_EFFORT_ID AS PROJECT_ID, P.WORK_EFFORT_NAME AS PROJECT_NAME, T.WORK_EFFORT_ID AS TASK_ID, T.WORK_EFFORT_NAME AS TASK_NAME,
<#if showParty?if_exists?has_content && "Y" == showParty>
	A.PARTY_ID, PP.PARTY_NAME,
</#if> 
T.ESTIMATED_START_DATE, T.ESTIMATED_COMPLETION_DATE,
SUM(A.HOURS) AS HOURS 
FROM <@table "TIME_ENTRY"/> A
INNER JOIN <@table "PARTY"/> PP ON PP.PARTY_ID = A.PARTY_ID
INNER JOIN <@table "WORK_EFFORT"/> T ON T.WORK_EFFORT_ID = A.WORK_EFFORT_ID
INNER JOIN <@table "WORK_EFFORT"/> F ON F.WORK_EFFORT_ID = T.WORK_EFFORT_PARENT_ID
INNER JOIN <@table "WORK_EFFORT"/> P ON P.WORK_EFFORT_ID = F.WORK_EFFORT_PARENT_ID
INNER JOIN <@table "WORK_EFFORT_ASSOC"/> S ON S.WORK_EFFORT_ID_TO = P.WORK_EFFORT_ID AND P.WORK_EFFORT_TYPE_ID = 'PROJECT'
INNER JOIN <@table "WORK_EFFORT"/> W ON W.WORK_EFFORT_ID = S.WORK_EFFORT_ID_FROM
WHERE W.WORK_EFFORT_ID = <@param workEffortId /> AND A.FROM_DATE >= W.ESTIMATED_START_DATE AND A.FROM_DATE <= W.ESTIMATED_COMPLETION_DATE

GROUP BY P.WORK_EFFORT_ID, P.WORK_EFFORT_NAME, T.WORK_EFFORT_ID, T.WORK_EFFORT_NAME,
<#if showParty?if_exists?has_content && "Y" == showParty>
	A.PARTY_ID, PP.PARTY_NAME,
</#if> 
T.ESTIMATED_START_DATE, T.ESTIMATED_COMPLETION_DATE

ORDER BY PROJECT_ID, PROJECT_NAME, TASK_ID, TASK_NAME,
<#if showParty?if_exists?has_content && "Y" == showParty>
	PARTY_ID, PARTY_NAME,
</#if> 
ESTIMATED_START_DATE, ESTIMATED_COMPLETION_DATE
