CREATE VIEW WORK_EFFORT_ASSOC_VIEW (
    WE_FROM_ID, WE_FROM_CODE, WE_FROM_ETCH, 
    WE_FROM_START_DATE, WE_FROM_COMPLETION_DATE,
    WE_FROM_NAME, WE_FROM_NAME_LANG, WE_FROM_TYPE_ID, WE_FROM_TYPE_ETCH, WE_FROM_TYPE_ETCH_LANG, WE_FROM_REVISION_ID,
	WE_FROM_PARENT_ID, WE_FROM_ASSOC_TYPE_ID, WE_FROM_HIERARCHY_TYPE_ID,
	WE_FROM_ORG_ROLE_ID, WE_FROM_ORG_UNIT_ID,
	WE_FROM_DESCR, WE_FROM_DESCR_LANG, WE_FROM_RANGE_SCORE,
	WE_ASS_TYPE_ID, WE_ASS_PARENT_TYPE_ID, WE_ASS_SEQ_NUM,
    WE_ASS_WEIGHT, WE_ASS_COMMENTS, WE_ASS_NOTE,
    WE_TO_ID, WE_TO_CODE, WE_TO_ETCH,
    WE_TO_NAME, WE_TO_NAME_LANG, WE_TO_TYPE_ID, WE_TO_TYPE_ETCH, WE_TO_TYPE_ETCH_LANG , 
    WE_TO_START_DATE, WE_TO_COMPLETION_DATE, WE_TO_REVISION_ID,
	wE_TO_PARENT_ID, WE_TO_ASSOC_TYPE_ID, WE_TO_HIERARCHY_TYPE_ID,
	WE_TO_ORG_ROLE_ID, WE_TO_ORG_UNIT_ID,
	WE_TO_DESCR, WE_TO_DESCR_LANG, WE_TO_RANGE_SCORE, WA_FROM_DATE, WA_THRU_DATE
) AS
SELECT 
    WA.WORK_EFFORT_ID_FROM, WF.SOURCE_REFERENCE_ID, WF.ETCH,
    WF.ESTIMATED_START_DATE , WF.ESTIMATED_COMPLETION_DATE , 
    WF.WORK_EFFORT_NAME, WF.WORK_EFFORT_NAME_LANG, WF.WORK_EFFORT_TYPE_ID, WFT.ETCH, WFT.ETCH_LANG, WF.WORK_EFFORT_REVISION_ID,
	WF.WORK_EFFORT_PARENT_ID, WF.WORK_EFFORT_ASSOC_TYPE_ID, WFT.HIERARCHY_ASSOC_TYPE_ID, 
	WF.ORG_UNIT_ROLE_TYPE_ID, WF.ORG_UNIT_ID,
	WF.DESCRIPTION, WF.DESCRIPTION_LANG, COALESCE(WF.UOM_RANGE_SCORE_ID, WFT.UOM_RANGE_SCORE_ID),
	WA.WORK_EFFORT_ASSOC_TYPE_ID, WAT.PARENT_TYPE_ID, WA.SEQUENCE_NUM,
    WA.ASSOC_WEIGHT, WA.COMMENTS, WA.NOTE,
    WA.WORK_EFFORT_ID_TO, WT.SOURCE_REFERENCE_ID, WT.ETCH,
    WT.WORK_EFFORT_NAME, WT.WORK_EFFORT_NAME_LANG, WT.WORK_EFFORT_TYPE_ID, WTT.ETCH, WTT.ETCH_LANG, 
    WT.ESTIMATED_START_DATE , WT.ESTIMATED_COMPLETION_DATE, WT.WORK_EFFORT_REVISION_ID,
	WT.WORK_EFFORT_PARENT_ID, WT.WORK_EFFORT_ASSOC_TYPE_ID, WTT.HIERARCHY_ASSOC_TYPE_ID,
	WT.ORG_UNIT_ROLE_TYPE_ID, WT.ORG_UNIT_ID,
	WT.DESCRIPTION, WT.DESCRIPTION_LANG, COALESCE(WT.UOM_RANGE_SCORE_ID, WTT.UOM_RANGE_SCORE_ID), WA.FROM_DATE, WA.THRU_DATE
FROM WORK_EFFORT_ASSOC WA
INNER JOIN WORK_EFFORT_ASSOC_TYPE WAT
    ON WAT.WORK_EFFORT_ASSOC_TYPE_ID = WA.WORK_EFFORT_ASSOC_TYPE_ID
INNER JOIN WORK_EFFORT WF
    ON WF.WORK_EFFORT_ID = WA.WORK_EFFORT_ID_FROM
INNER JOIN WORK_EFFORT_TYPE WFT
    ON WFT.WORK_EFFORT_TYPE_ID = WF.WORK_EFFORT_TYPE_ID
INNER JOIN WORK_EFFORT WT
    ON WT.WORK_EFFORT_ID = WA.WORK_EFFORT_ID_TO
INNER JOIN WORK_EFFORT_TYPE WTT
    ON WTT.WORK_EFFORT_TYPE_ID = WT.WORK_EFFORT_TYPE_ID
WHERE (WA.THRU_DATE = WF.ESTIMATED_COMPLETION_DATE
   OR WA.THRU_DATE = WT.ESTIMATED_COMPLETION_DATE)
  AND WA.WORK_EFFORT_ASSOC_TYPE_ID NOT IN ('ROOT', 'TEMPL')
  AND (WAT.PARENT_TYPE_ID IS NULL OR WAT.PARENT_TYPE_ID <> 'TECHNICAL');