SELECT WTIC.CONTENT_ID, A.WORK_EFFORT_ID, A.WORK_EFFORT_MEASURE_ID, A.UOM_RANGE_ID, A.UOM_DESCR, A.GL_ACCOUNT_ID, A.PRODUCT_ID, A.EMPL_POSITION_TYPE_ID,
A.ROLE_TYPE_ID AS MEASURE_ROLE_TYPE_ID, A.PARTY_ID AS MEASURE_PARTY_ID, A.WE_MEASURE_TYPE_ENUM_ID, A.WE_OTHER_GOAL_ENUM_ID, A.FROM_DATE, A.THRU_DATE, B.SOURCE_REFERENCE_ID,
B.WORK_EFFORT_NAME, B.ETCH, B.WORK_EFFORT_TYPE_ID,D.ACT_ST_ENUM_ID, E.ACCOUNT_CODE, E.ACCOUNT_NAME, 
F.UOM_TYPE_ID,
F.ABBREVIATION,
G.B_AMOUNT, G.A_TRANSACTION_DATE, 
G.A_GL_FISCAL_TYPE_ID,
G.C_DESCRIPTION, 
G.A_DESCRIPTION, 
G.B_DESCRIPTION, 
G.A_ACCTG_TRANS_ID, 
G.B_ACCTG_TRANS_ENTRY_SEQ_ID, H.DESCRIPTION, I.DESCRIPTION, L.DESCRIPTION, M.PARTY_NAME,
PP.PARENT_ROLE_CODE, O.UOM_CODE, O.UOM_DESCR, P.CUSTOM_TIME_PERIOD_ID, P.PERIOD_NAME, P.IS_CLOSED
, G.DEBIT_CREDIT_FLAG,
E.DEBIT_CREDIT_DEFAULT,
E.PERIODICAL_ABSOLUTE_ENUM_ID,
G.PERIODICAL_ABSOLUTE_ENUM_ID  , E.GL_RESOURCE_TYPE_ID 
, A.GL_ACCOUNT_ID
,E.GL_ACCOUNT_TYPE_ID,
 F.ABBREVIATION
,E.DESCRIPTION AS ACCOUNT_DESCRIPTION 
,E.DETAIL_ENUM_ID
,E.INPUT_ENUM_ID
,E.DETECT_ORG_UNIT_ID_FLAG
,E.DATA_SOURCE_ID
,E.DEFAULT_UOM_ID
,A.COMMENTS
,A.SEQUENCE_ID
,F.DECIMAL_SCALE
,A.KPI_SCORE_WEIGHT
,A.DATA_SOURCE_ID
,G.B_CURRENCY_UOM_ID
,G.B_PERF_AMOUNT_CALC
,G.B_HAS_SCORE_ALERT 
,G.B_GL_ACCOUNT_ID  
,G.A_WORK_EFFORT_SNAPSHOT_ID
,E.ACCOUNT_TYPE_ENUM_ID  
,G.B_GL_FISCAL_TYPE_ID  
,G.B_VOUCHER_REF
,B.ORG_UNIT_ROLE_TYPE_ID
,B.ORG_UNIT_ID
,AT.IS_POSTED
,G.A_PARTY_ID AS PARTY_ID
,G.A_ROLE_TYPE_ID AS ROLE_TYPE_ID 
,G.B_PARTY_ID AS ENTRY_PARTY_ID
,G.B_ROLE_TYPE_ID AS ENTRY_ROLE_TYPE_ID 
, DT.DATA_SOURCE_ID AS DATA_SOURCE_ID, DT.VAL_MOD_ID AS VAL_MOD_ID, DTP.DATA_SOURCE_ID AS WM_DATA_SOURCE_ID, DTP.VAL_MOD_ID AS WM_VAL_MOD_ID,
CASE WHEN (INPUT_ENUM_ID = 'ACCINP_OBJ' OR INPUT_ENUM_ID = 'ACCINP_UO') THEN E.RESP_CENTER_ROLE_TYPE_ID ELSE B.ORG_UNIT_ROLE_TYPE_ID END AS ORG_UNIT_ROLE_TYPE_ID,
CASE WHEN (INPUT_ENUM_ID = 'ACCINP_OBJ' OR INPUT_ENUM_ID = 'ACCINP_UO') THEN E.RESP_CENTER_ID ELSE B.ORG_UNIT_ID END AS ORG_UNIT_ID

FROM <@table "WORK_EFFORT_MEASURE"/> A
INNER JOIN <@table "WORK_EFFORT"/> B ON A.WORK_EFFORT_ID = B.WORK_EFFORT_ID
INNER JOIN <@table "STATUS_ITEM"/> D ON B.CURRENT_STATUS_ID = D.STATUS_ID
INNER JOIN <@table "GL_ACCOUNT"/> E ON A.GL_ACCOUNT_ID = E.GL_ACCOUNT_ID
INNER JOIN <@table "UOM"/> F ON E.DEFAULT_UOM_ID = F.UOM_ID
INNER JOIN <@table "WORK_EFFORT_TYPE_CONTENT"/> WTIC ON WTIC.WORK_EFFORT_TYPE_ID = B.WORK_EFFORT_TYPE_ID
INNER JOIN <@table "WORK_EFFORT_PURPOSE_ACCOUNT"/> WA ON WA.GL_ACCOUNT_ID = E.GL_ACCOUNT_ID
	AND WA.WORK_EFFORT_PURPOSE_TYPE_ID =  WTIC.WORK_EFFORT_PURPOSE_TYPE_ID
	
LEFT OUTER JOIN <@table "ACCTG_TRANS_VIEW"/> G
  ON (
      (
        (E.INPUT_ENUM_ID = 'ACCINP_OBJ' AND G.B_GL_ACCOUNT_ID <> 'SCOREKPI') 
        AND A.WORK_EFFORT_MEASURE_ID = G.B_VOUCHER_REF
      ) OR (
        (E.INPUT_ENUM_ID <> 'ACCINP_OBJ' AND G.B_GL_ACCOUNT_ID <> 'SCOREKPI') 
        AND G.B_ORGANIZATION_PARTY_ID = B.ORGANIZATION_ID 
        AND ((A.PRODUCT_ID IS NULL  AND G.B_PRODUCT_ID IS NULL )OR A.PRODUCT_ID = G.B_PRODUCT_ID)
        AND ((A.EMPL_POSITION_TYPE_ID IS NULL AND G.B_EMPL_POSITION_TYPE_ID IS NULL )OR A.EMPL_POSITION_TYPE_ID = G.B_EMPL_POSITION_TYPE_ID)
        AND ((A.ROLE_TYPE_ID IS NULL AND A.PARTY_ID IS NULL AND G.B_ROLE_TYPE_ID IS NULL AND  G.B_PARTY_ID IS NULL)
           OR (A.ROLE_TYPE_ID = G.B_ROLE_TYPE_ID AND A.PARTY_ID = G.B_PARTY_ID)
           OR (A.ROLE_TYPE_ID IS NULL AND A.PARTY_ID IS NULL  AND E.DETAIL_ENUM_ID <> 'ACCDET_NULL') 
          ) 
        AND ((A.GL_ACCOUNT_ID = G.B_GL_ACCOUNT_ID AND E.ACCOUNT_TYPE_ENUM_ID <> 'FINANCIAL')
           OR (A.GL_ACCOUNT_ID = G.B_GL_ACCOUNT_FIN_ID AND E.ACCOUNT_TYPE_ENUM_ID = 'FINANCIAL'))
        AND G.B_ORGANIZATION_PARTY_ID = B.ORGANIZATION_ID 
        AND ((A.WE_OTHER_GOAL_ENUM_ID = 'WEMOMG_WEFF' AND G.A_WORK_EFFORT_ID = A.WORK_EFFORT_ID)
           OR (A.WE_OTHER_GOAL_ENUM_ID <> 'WEMOMG_WEFF' AND A.OTHER_WORK_EFFORT_ID IS NOT NULL
              AND G.A_WORK_EFFORT_ID = A.OTHER_WORK_EFFORT_ID)
           OR (A.WE_OTHER_GOAL_ENUM_ID <> 'WEMOMG_WEFF' AND A.OTHER_WORK_EFFORT_ID IS NULL))
        AND (A.WE_OTHER_GOAL_ENUM_ID <> 'WEMOMG_ORG'
          OR (B.ORG_UNIT_ROLE_TYPE_ID = G.A_ROLE_TYPE_ID AND B.ORG_UNIT_ID = G.A_PARTY_ID))
      )
    )

    AND ((B.WORK_EFFORT_SNAPSHOT_ID IS NULL AND G.A_WORK_EFFORT_SNAPSHOT_ID IS NULL)
          OR  (B.WORK_EFFORT_SNAPSHOT_ID IS NOT NULL AND G.A_WORK_EFFORT_SNAPSHOT_ID IS NOT NULL AND B.WORK_EFFORT_SNAPSHOT_ID = G.A_WORK_EFFORT_SNAPSHOT_ID))
    
    <#if glFiscalTypeId?if_exists?has_content>
    	AND G.A_GL_FISCAL_TYPE_ID = <@param glFiscalTypeId />
    </#if>
    
    <#if weTransDate?if_exists?has_content>
    	AND G.A_TRANSACTION_DATE = <@param weTransDate jdbcType.TIMESTAMP />
	</#if>
	
LEFT OUTER JOIN <@table "ACCTG_TRANS"/> AT ON AT.ACCTG_TRANS_ID = G.A_ACCTG_TRANS_ID	

LEFT OUTER JOIN <@table "PRODUCT"/> H ON A.PRODUCT_ID = H.PRODUCT_ID
LEFT OUTER JOIN <@table "EMPL_POSITION_TYPE"/> I ON A.EMPL_POSITION_TYPE_ID = I.EMPL_POSITION_TYPE_ID
LEFT OUTER JOIN <@table "ROLE_TYPE"/> L ON G.B_ROLE_TYPE_ID = L.ROLE_TYPE_ID
LEFT OUTER JOIN <@table "PARTY"/> M     ON G.B_PARTY_ID     = M.PARTY_ID
LEFT OUTER JOIN <@table "PARTY_ROLE"/>  PR
ON  G.B_PARTY_ID     = PR.PARTY_ID
AND G.B_ROLE_TYPE_ID = PR.ROLE_TYPE_ID
LEFT OUTER JOIN PARTY_PARENT_ROLE PP
ON  PR.PARTY_ID            = PP.PARTY_ID
AND PR.PARENT_ROLE_TYPE_ID = PP.ROLE_TYPE_ID
LEFT OUTER JOIN <@table "WORK_EFFORT_MEAS_RAT_SC"/> O ON A.WORK_EFFORT_MEASURE_ID = O.WORK_EFFORT_MEASURE_ID
                 AND O.UOM_ID = G.B_CURRENCY_UOM_ID AND O.UOM_RATING_VALUE = G.B_AMOUNT
LEFT OUTER JOIN <@table "CUSTOM_TIME_PERIOD"/> P ON A. PERIOD_TYPE_ID = P.PERIOD_TYPE_ID
                 AND P.FROM_DATE <= G.A_TRANSACTION_DATE
                 AND P.THRU_DATE >= G.A_TRANSACTION_DATE
                 
LEFT OUTER JOIN <@table "DATA_SOURCE"/> DT ON DT.DATA_SOURCE_ID = E.DATA_SOURCE_ID

LEFT OUTER JOIN <@table "DATA_SOURCE"/> DTP ON DTP.DATA_SOURCE_ID = A.DATA_SOURCE_ID

LEFT OUTER JOIN <@table "GL_FISCAL_TYPE"/> GL ON GL.GL_FISCAL_TYPE_ID = G.A_GL_FISCAL_TYPE_ID

WHERE A.WORK_EFFORT_ID = <@param workEffortId />
<#if contentId?if_exists?has_content>
	AND WTIC.CONTENT_ID = <@param contentId />
</#if>
<#if weTransCurrencyUomId?if_exists?has_content>
	AND E.DEFAULT_UOM_ID = <@param weTransCurrencyUomId />
</#if>
<#if workEffortMeasureId?if_exists?has_content>
    AND A.WORK_EFFORT_MEASURE_ID = <@param workEffortMeasureId />
</#if>

ORDER BY A.SEQUENCE_ID, E.ACCOUNT_CODE, G.A_TRANSACTION_DATE DESC, G.A_GL_FISCAL_TYPE_ID