SELECT TM.WORK_EFFORT_ID AS WE_TRANS_WE_ID
, TM.VOUCHER_REF AS WE_TRANS_MEASURE_ID
, TR.ACCTG_TRANS_ID AS WE_TRANS_ID
, TR.ACCTG_TRANS_ENTRY_SEQ_ID AS WE_TRANS_ENTRY_ID
, TR.AMOUNT AS WE_TRANS_VALUE
, TM.TRANSACTION_DATE AS WE_TRANS_DATE
, TR.GL_ACCOUNT_ID AS WE_TRANS_ACCOUNT_ID
, M.WE_MEASURE_TYPE_ENUM_ID AS WE_MEASURE_MEASURE_TYPE
, TM.GL_FISCAL_TYPE_ID AS WE_TRANS_TYPE_VALUE_ID
, TM.GROUP_STATUS_ID
, TM.DESCRIPTION AS WE_TRANS_COMMENTS
, TM.DESCRIPTION_LANG AS WE_TRANS_COMMENTS_LANG
, TR.GL_ACCOUNT_ID AS WE_ACCTG_TRANS_ACCOUNT_ID
, TR.GL_ACCOUNT_FIN_ID AS WE_ACCTG_TRANS_ACCOUNT_FIN_ID
, TM.IS_POSTED
, TM.GL_FISCAL_TYPE_ID AS WE_TRANS_TYPE_VALUE_ID
, TR.WORK_EFFORT_SNAPSHOT_ID AS WE_TRANS_WORK_EFFORT_SNAP_SHOT_ID
, TR.WORK_EFFORT_REVISION_ID AS WE_TRANS_WORK_EFFORT_REVISION_ID
, GA.GL_RESOURCE_TYPE_ID
, GA.ACCOUNT_NAME AS WE_TRANS_ACCOUNT_DESC
, GA.ACCOUNT_CODE AS WE_TRANS_ACCOUNT_CODE
, GF.DESCRIPTION AS WE_TRANS_TYPE_VALUE_DESC
, RS.UOM_CODE AS WE_TRANS_VALUE_CODE
, TR.CURRENCY_UOM_ID AS WE_TRANS_CURRENCY_UOM_ID
, TR.DESCRIPTION AS WE_TRANS_COMMENT
, TR.DESCRIPTION_LANG AS WE_TRANS_COMMENT_LANG
, TR.ORIG_AMOUNT
, TR.PRODUCT_ID AS TRANS_PRODUCT_ID
, RS.UOM_DESCR AS WE_TRANS_VALUE_DESC
, M.UOM_DESCR AS WE_TRANS_UOM_DESC
, U.UOM_TYPE_ID AS WE_TRANS_UOM_TYPE
, U.DECIMAL_SCALE AS WE_TRANS_DECIMAL_SCALE
, CT.IS_CLOSED AS WE_TRANS_PERIOD_IS_CLOSED
, CT.PERIOD_TYPE_ID
, CT.CUSTOM_TIME_PERIOD_ID
, TM.WORK_EFFORT_SNAPSHOT_ID AS WE_TRANS_WORK_EFFORT_SNAPSHOT_ID
, WDS.VAL_MOD_ID AS WM_VAL_MOD_ID
, GDS.VAL_MOD_ID AS GL_VAL_MOD_ID
, GA.INPUT_ENUM_ID

FROM <@table "ACCTG_TRANS"/> TM
INNER JOIN <@table "ACCTG_TRANS_ENTRY"/> TR ON TM.ACCTG_TRANS_ID = TR.ACCTG_TRANS_ID
INNER JOIN <@table "GL_FISCAL_TYPE"/> GF ON GF.GL_FISCAL_TYPE_ID = TM.GL_FISCAL_TYPE_ID
INNER JOIN <@table "GL_ACCOUNT"/> GA ON GA.GL_ACCOUNT_ID = TR.GL_ACCOUNT_ID
INNER JOIN <@table "UOM"/> U ON GA.DEFAULT_UOM_ID = U.UOM_ID
LEFT OUTER JOIN <@table "WORK_EFFORT"/> W ON W.WORK_EFFORT_ID = TM.WORK_EFFORT_ID
LEFT OUTER JOIN <@table "WORK_EFFORT_MEASURE"/> M ON M.WORK_EFFORT_MEASURE_ID = TM.VOUCHER_REF
LEFT OUTER JOIN <@table "WORK_EFFORT_MEAS_RAT_SC"/> RS ON RS.WORK_EFFORT_MEASURE_ID = M.WORK_EFFORT_MEASURE_ID
	AND RS.UOM_ID = TR.CURRENCY_UOM_ID AND RS.UOM_RATING_VALUE = TR.AMOUNT
LEFT OUTER JOIN <@table "CUSTOM_TIME_PERIOD"/> CT ON CT.PERIOD_TYPE_ID = M.PERIOD_TYPE_ID
	AND CT.THRU_DATE =  TM.TRANSACTION_DATE
         
LEFT OUTER JOIN <@table "DATA_SOURCE"/> GDS ON GDS.DATA_SOURCE_ID = GA.DATA_SOURCE_ID

LEFT OUTER JOIN <@table "DATA_SOURCE"/> WDS ON WDS.DATA_SOURCE_ID = M.DATA_SOURCE_ID

WHERE TM.WORK_EFFORT_ID = <@param workEffortId /> AND 
TR.VOUCHER_REF = <@param workEffortMeasureId /> 
OR ( TR.VOUCHER_REF IS NULL AND TR.GL_ACCOUNT_FIN_ID = <@param glAccountId /> )

ORDER BY WE_MEASURE_MEASURE_TYPE, WE_TRANS_ACCOUNT_CODE, WE_TRANS_MEASURE_ID, WE_TRANS_DATE, WE_TRANS_TYPE_VALUE_DESC
