 CREATE VIEW MEASURE_AND_PRODUCT_VIEW (
 WM_GL_ACCOUNT_ID,
 PR_INTERNAL_NAME,
 PR_PRODUCT_ID,
 PR_PRODUCT_MAIN_CODE,
 WM_UOM_DESCR,
 WM_UOM_DESCR_LANG,
 WM_DETAIL_ENUM_ID,
 ORG_UNIT_ID,
 ORG_UNIT_ROLE_TYPE_ID,
 ORG_UNIT_NAME,
 ORG_UNIT_NAME_LANG
 )
AS SELECT 
        WM.GL_ACCOUNT_ID AS WM_GL_ACCOUNT_ID,
            PR.INTERNAL_NAME AS PR_INTERNAL_NAME,
            PR.PRODUCT_ID AS PR_PRODUCT_ID,
            PR.PRODUCT_MAIN_CODE AS PR_PRODUCT_MAIN_CODE,
            WM.UOM_DESCR AS WM_UOM_DESCR,
            WM.UOM_DESCR_LANG AS WM_UOM_DESCR_LANG,
            WM.DETAIL_ENUM_ID AS WM_DETAIL_ENUM_ID,
            WM.ORG_UNIT_ID AS ORG_UNIT_ID,
            WM.ORG_UNIT_ROLE_TYPE_ID AS ORG_UNIT_ROLE_TYPE_ID,
            PG.GROUP_NAME AS ORG_UNIT_NAME,
            PG.GROUP_NAME_LANG AS ORG_UNIT_NAME_LANG
    FROM
        WORK_EFFORT_MEASURE WM
    INNER JOIN PRODUCT PR ON WM.PRODUCT_ID = PR.PRODUCT_ID
    LEFT OUTER JOIN PARTY_GROUP PG ON WM.ORG_UNIT_ID = PG.PARTY_ID
WHERE WM.WORK_EFFORT_ID IS NULL
