SELECT SUM(WEPA.ROLE_TYPE_WEIGHT) AS SUM_ROLE_TYPE_WEIGHT
FROM <@table "WORK_EFFORT_PARTY_ASSIGNMENT"/> WEPA 
INNER JOIN <@table "WORK_EFFORT"/> WE ON WE.WORK_EFFORT_ID = WEPA.WORK_EFFORT_ID
WHERE (
		WEPA.PARTY_ID = <@param partyId />
		AND	WEPA.ROLE_TYPE_ID = 'WE_ASSIGNMENT' AND WE.WORK_EFFORT_SNAPSHOT_ID IS NULL 
		AND WEPA.WORK_EFFORT_ID_FROM IS NULL
		AND WEPA.FROM_DATE <= <@param thruDate jdbcType.TIMESTAMP /> AND WEPA.THRU_DATE >= <@param thruDate jdbcType.TIMESTAMP />
)
GROUP by WEPA.PARTY_ID
ORDER BY WEPA.PARTY_ID
