CREATE VIEW WORK_EFFORT_TRANS_INDIC_VIEW (
    M_WORK_EFFORT_ID, M_WORK_EFFORT_MEASURE_ID, M_UOM_RANGE_ID, M_UOM_DESCR, M_GL_ACCOUNT_ID, M_PRODUCT_ID, M_EMPL_POSITION_TYPE_ID,
    M_ROLE_TYPE_ID, M_PARTY_ID, M_WE_MEASURE_TYPE_ENUM_ID, M_WE_OTHER_GOAL_ENUM_ID, M_FROM_DATE, M_THRU_DATE, W_SOURCE_REFERENCE_ID,
    W_WORK_EFFORT_NAME, W_ETCH, 
    W_WORK_EFFORT_TYPE_ID,
    S_ACT_ST_ENUM_ID, G_ACCOUNT_CODE, G_ACCOUNT_NAME, G_UOM_TYPE_ID, G_UOM_ABBREVIATION,TM_AMOUNT, TT_TRANSACTION_DATE, 
    TT_GL_FISCAL_TYPE_ID,
    TT_FISCAL_TYPE_DESCRIPTION, 
    TT_DESCRIPTION,
    TT_DESCRIPTION_LANG,
    TM_DESCRIPTION,
    TM_DESCRIPTION_LANG,
    TM_ACCTG_TRANS_ID, TM_ACCTG_TRANS_ENTRY_SEQ_ID, M_PRODUCT_DESCRIPTION, M_POSITION_DESCRIPTION, M_ROLE_TYPE_DESCRIPTION, 
    
    
    TT_PARTY_ID,
    TT_ROLE_TYPE_ID, 
    TM_PARTY_ID,
    TM_ROLE_TYPE_ID, 
  
    M_PARTY_NAME,
    M_PARENT_ROLE_CODE, 
    R_UOM_CODE, R_UOM_CODE_LANG, R_UOM_DESCR, 
    M_CUSTOM_TIME_PERIOD_ID,
    M_PERIOD_NAME, M_PERIOD_IS_CLOSED,
    TM_DEBIT_CREDIT_FLAG,
    G_DEBIT_CREDIT_DEFAULT,
    G_PERIODICAL_ABSOLUTE_ENUM_ID,
    TT_PERIODICAL_ABSOLUTE_ENUM_ID
    , G_GL_RESOURCE_TYPE_ID 
    , G_GL_ACCOUNT_ID
    , G_GL_ACCOUNT_TYPE_ID
    , G_UOM_CODE
    ,G_DESCRIPTION 
    ,G_DETAIL_ENUM_ID
    ,G_INPUT_ENUM_ID
    ,M_COMMENTS
	,M_SEQUENCE_ID
	,G_UOM_DECIMAL_SCALE
	,M_KPI_SCORE_WEIGHT
	,M_KPI_OTHER_WEIGHT
	,G_CURRENCY_UOM_ID
	,G_PERF_AMOUNT_CALC
	,G_PERF_AMOUNT_ACTUAL
    ,G_PERF_AMOUNT_TARGET
    ,R_PERF_ACT_UOM_CODE
  	,R_PERF_TAR_UOM_CODE    
	,G_HAS_SCORE_ALERT
	,TM_GL_ACCOUNT_ID
	,G_WORK_EFFORT_SNAPSHOT_ID
	,G_ACCOUNT_TYPE_ENUM_ID
	,TM_GL_FISCAL_TYPE_ID
	,TM_VOUCHER_REF
	
	,TT_IS_POSTED
	
	,M_ORG_UNIT_ROLE_TYPE_ID
	,M_ORG_UNIT_ID,
	G_WORK_EFFORT_REVISION_ID,
	G_CHECK_AMOUNT1,
    G_CHECK_AMOUNT2,
    G_CHECK_AMOUNT3,
    G_TEXT_VALUE1
	
) AS
SELECT A.WORK_EFFORT_ID, A.WORK_EFFORT_MEASURE_ID, A.UOM_RANGE_ID, A.UOM_DESCR, A.GL_ACCOUNT_ID, A.PRODUCT_ID, A.EMPL_POSITION_TYPE_ID,
  A.ROLE_TYPE_ID, A.PARTY_ID, A.WE_MEASURE_TYPE_ENUM_ID, A.WE_OTHER_GOAL_ENUM_ID, A.FROM_DATE, A.THRU_DATE, B.SOURCE_REFERENCE_ID,
  B.WORK_EFFORT_NAME, B.ETCH, B.WORK_EFFORT_TYPE_ID,D.ACT_ST_ENUM_ID, E.ACCOUNT_CODE, E.ACCOUNT_NAME, 
  F.UOM_TYPE_ID,
  F.ABBREVIATION,
  G.B_AMOUNT, G.A_TRANSACTION_DATE, 
  G.A_GL_FISCAL_TYPE_ID,
  G.C_DESCRIPTION, 
  G.A_DESCRIPTION, 
  G.A_DESCRIPTION_LANG,
  G.B_DESCRIPTION, 
  G.B_DESCRIPTION_LANG, 
  G.A_ACCTG_TRANS_ID, 
  G.B_ACCTG_TRANS_ENTRY_SEQ_ID, H.DESCRIPTION, I.DESCRIPTION, L.DESCRIPTION,
  
  G.A_PARTY_ID,
  G.A_ROLE_TYPE_ID, 
  G.B_PARTY_ID,
  G.B_ROLE_TYPE_ID, 
  
  M.PARTY_NAME,
  PP.PARENT_ROLE_CODE, 
  O.UOM_CODE, O.UOM_CODE_LANG, O.UOM_DESCR, 
  P.CUSTOM_TIME_PERIOD_ID,
  P.PERIOD_NAME, P.IS_CLOSED
  , G.DEBIT_CREDIT_FLAG,
  E.DEBIT_CREDIT_DEFAULT,
  E.PERIODICAL_ABSOLUTE_ENUM_ID,
  G.PERIODICAL_ABSOLUTE_ENUM_ID  , E.GL_RESOURCE_TYPE_ID 
  , A.GL_ACCOUNT_ID
  ,E.GL_ACCOUNT_TYPE_ID,
   F.ABBREVIATION
  ,E.DESCRIPTION 
  ,E.DETAIL_ENUM_ID
  ,E.INPUT_ENUM_ID
  ,A.COMMENTS
  ,A.SEQUENCE_ID
  ,F.DECIMAL_SCALE
  ,A.KPI_SCORE_WEIGHT
  ,A.KPI_OTHER_WEIGHT
  ,G.B_CURRENCY_UOM_ID
  ,G.B_PERF_AMOUNT_CALC
  ,G.B_PERF_AMOUNT_ACTUAL
  ,G.B_PERF_AMOUNT_TARGET
  ,O_A.UOM_CODE
  ,O_T.UOM_CODE
  ,G.B_HAS_SCORE_ALERT 
  ,G.B_GL_ACCOUNT_ID  
  ,G.A_WORK_EFFORT_SNAPSHOT_ID
  ,E.ACCOUNT_TYPE_ENUM_ID  
  ,G.B_GL_FISCAL_TYPE_ID  
  ,G.B_VOUCHER_REF
  ,G.A_IS_POSTED
  ,B.ORG_UNIT_ROLE_TYPE_ID
  ,B.ORG_UNIT_ID,
  G.A_WORK_EFFORT_REVISION_ID,
  G.B_CHECK_AMOUNT1,
  G.B_CHECK_AMOUNT2,
  G.B_CHECK_AMOUNT3,
  G.B_TEXT_VALUE1
  
FROM WORK_EFFORT_MEASURE A
  INNER JOIN WORK_EFFORT B ON A.WORK_EFFORT_ID = B.WORK_EFFORT_ID
  INNER JOIN STATUS_ITEM D ON B.CURRENT_STATUS_ID = D.STATUS_ID
  INNER JOIN GL_ACCOUNT E ON A.GL_ACCOUNT_ID = E.GL_ACCOUNT_ID
  INNER JOIN UOM F ON E.DEFAULT_UOM_ID = F.UOM_ID
  LEFT OUTER JOIN ACCTG_TRANS_VIEW G
    ON (((E.INPUT_ENUM_ID = 'ACCINP_OBJ' OR G.B_GL_ACCOUNT_ID = 'SCOREKPI') AND A.WORK_EFFORT_MEASURE_ID = G.B_VOUCHER_REF)
     OR ((E.INPUT_ENUM_ID <> 'ACCINP_OBJ' AND G.B_GL_ACCOUNT_ID <> 'SCOREKPI')AND G.B_ORGANIZATION_PARTY_ID = B.ORGANIZATION_ID AND
     ((A.PRODUCT_ID IS NULL  AND G.B_PRODUCT_ID IS NULL )OR A.PRODUCT_ID = G.B_PRODUCT_ID)
           AND ((A.EMPL_POSITION_TYPE_ID IS NULL AND G.B_EMPL_POSITION_TYPE_ID IS NULL )OR A.EMPL_POSITION_TYPE_ID = G.B_EMPL_POSITION_TYPE_ID)
           AND ((A.ROLE_TYPE_ID IS NULL AND A.PARTY_ID IS NULL AND G.B_ROLE_TYPE_ID IS NULL AND  G.B_PARTY_ID IS NULL)
             OR (A.ROLE_TYPE_ID = G.B_ROLE_TYPE_ID AND A.PARTY_ID = G.B_PARTY_ID)
             OR (A.ROLE_TYPE_ID IS NULL AND A.PARTY_ID IS NULL  AND E.DETAIL_ENUM_ID <> 'ACCDET_NULL') 
            ) 
           AND ((A.GL_ACCOUNT_ID = G.B_GL_ACCOUNT_ID AND E.ACCOUNT_TYPE_ENUM_ID <> 'FINANCIAL')
             OR (A.GL_ACCOUNT_ID = G.B_GL_ACCOUNT_FIN_ID AND E.ACCOUNT_TYPE_ENUM_ID = 'FINANCIAL'))
           AND G.B_ORGANIZATION_PARTY_ID = B.ORGANIZATION_ID 
           AND ((A.WE_OTHER_GOAL_ENUM_ID = 'WEMOMG_WEFF' AND G.A_WORK_EFFORT_ID = A.WORK_EFFORT_ID)
             OR (A.WE_OTHER_GOAL_ENUM_ID <> 'WEMOMG_WEFF' AND A.OTHER_WORK_EFFORT_ID IS NOT NULL
                AND G.A_WORK_EFFORT_ID = A.OTHER_WORK_EFFORT_ID)
             OR (A.WE_OTHER_GOAL_ENUM_ID <> 'WEMOMG_WEFF' AND A.OTHER_WORK_EFFORT_ID IS NULL))
           AND (A.WE_OTHER_GOAL_ENUM_ID <> 'WEMOMG_ORG'
            OR (B.ORG_UNIT_ROLE_TYPE_ID = G.A_ROLE_TYPE_ID AND B.ORG_UNIT_ID = G.A_PARTY_ID))
               ))
           AND ((B.WORK_EFFORT_SNAPSHOT_ID IS NULL AND G.A_WORK_EFFORT_SNAPSHOT_ID IS NULL)
            OR  (B.WORK_EFFORT_SNAPSHOT_ID IS NOT NULL AND G.A_WORK_EFFORT_SNAPSHOT_ID IS NOT NULL AND B.WORK_EFFORT_SNAPSHOT_ID = G.A_WORK_EFFORT_SNAPSHOT_ID))
  LEFT OUTER JOIN PRODUCT H ON A.PRODUCT_ID = H.PRODUCT_ID
  LEFT OUTER JOIN EMPL_POSITION_TYPE I ON A.EMPL_POSITION_TYPE_ID = I.EMPL_POSITION_TYPE_ID
  LEFT OUTER JOIN ROLE_TYPE L ON G.B_ROLE_TYPE_ID = L.ROLE_TYPE_ID
  LEFT OUTER JOIN PARTY M     ON G.B_PARTY_ID     = M.PARTY_ID
  LEFT OUTER JOIN PARTY_ROLE  PR
  ON  G.B_PARTY_ID     = PR.PARTY_ID
  AND G.B_ROLE_TYPE_ID = PR.ROLE_TYPE_ID
  LEFT OUTER JOIN PARTY_PARENT_ROLE PP
  ON  PR.PARTY_ID            = PP.PARTY_ID
  AND PR.PARENT_ROLE_TYPE_ID = PP.ROLE_TYPE_ID
  LEFT OUTER JOIN WORK_EFFORT_MEAS_RAT_SC O ON A.WORK_EFFORT_MEASURE_ID = O.WORK_EFFORT_MEASURE_ID
                   AND O.UOM_ID = G.B_CURRENCY_UOM_ID AND O.UOM_RATING_VALUE = G.B_AMOUNT
                   AND G.B_GL_ACCOUNT_ID NOT LIKE 'SCORE%'
  LEFT OUTER JOIN WORK_EFFORT_MEAS_RAT_SC O_A ON A.WORK_EFFORT_MEASURE_ID = O_A.WORK_EFFORT_MEASURE_ID
                   AND O_A.UOM_ID = G.B_CURRENCY_UOM_ID AND O_A.UOM_RATING_VALUE = G.B_PERF_AMOUNT_ACTUAL
  LEFT OUTER JOIN WORK_EFFORT_MEAS_RAT_SC O_T ON A.WORK_EFFORT_MEASURE_ID = O_T.WORK_EFFORT_MEASURE_ID
                   AND O_T.UOM_ID = G.B_CURRENCY_UOM_ID AND O_T.UOM_RATING_VALUE = G.B_PERF_AMOUNT_TARGET                 
  LEFT OUTER JOIN CUSTOM_TIME_PERIOD P ON A. PERIOD_TYPE_ID = P.PERIOD_TYPE_ID
                   AND P.FROM_DATE <= G.A_TRANSACTION_DATE
                   AND P.THRU_DATE >= G.A_TRANSACTION_DATE
;
