<#include "classpath://sql/FtlQuery-vendor-lib.ftl" />

SELECT 
  DISTINCT
  GL.RESP_CENTER_ID AS PARTY_ID,
  PR.PARTY_ID_TO AS PARTY_ID_TO,
  CM.CONTACT_MECH_ID AS CONTACT_MECH_ID_TO,
  <@convertFieldToVarcharMax "RWT.NOTE", "CONTENT" />,
  RWT.ETCH AS SUBJECT,
  <@convertFieldToVarcharMax "RWT.NOTE_LANG", "CONTENT_LANG" />,
  RWT.ETCH_LANG AS SUBJECT_LANG
FROM <@table "GL_ACCOUNT"/> GL
INNER JOIN <@table "PARTY_RELATIONSHIP"/> PR ON PR.PARTY_ID_FROM = GL.RESP_CENTER_ID
AND PR.PARTY_RELATIONSHIP_TYPE_ID = 'ORG_DELEGATE'
AND PR.FROM_DATE <= <@param monitoringDate jdbcType.TIMESTAMP />
AND (PR.THRU_DATE IS NULL OR PR.THRU_DATE >= <@param monitoringDate jdbcType.TIMESTAMP />)
INNER JOIN <@table "PARTY_ROLE"/> PR2 ON PR2.PARTY_ID = PR.PARTY_ID_TO AND PR2.ROLE_TYPE_ID = 'PRS_KPI'
INNER JOIN <@table "PARTY_CONTACT_MECH"/> PC ON PC.PARTY_ID = PR2.PARTY_ID
       AND PC.THRU_DATE IS NULL
INNER JOIN <@table "CONTACT_MECH"/> CM ON CM.CONTACT_MECH_ID = PC.CONTACT_MECH_ID
       AND CM.CONTACT_MECH_TYPE_ID = 'EMAIL_ADDRESS'
INNER JOIN <@table "WORK_EFFORT_TYPE"/> RWT ON RWT.WORK_EFFORT_TYPE_ID = 'SOLL_PRS'
WHERE GL.GL_ACCOUNT_TYPE_ID = 'INDPRS'