package com.mapsengineering.workeffortext.services.resource;

/**
 * Enumeration for query
 */
public enum I {
    workEffortId, workEffortMeasureId, glAccountId, glFiscalTypeId, searchDate, weTransCurrencyUomId, contentId, showScorekpi, yearEnd, yearStart, uomDescr,
    //
    weScoreConvEnumId, weScoreRangeEnumId, weAlertRuleEnumId, weMeasureTypeEnumId, weWithoutPerf, uomRangeId, kpiScoreWeight, inputEnumId, detailEnumId, calcCustomMethodId, 
    //
    glAccountTypeDescription, fromDate, thruDate, uomTypeId, sequenceId, productId, 
    //
    WE_TRANS_WE_ID, WE_TRANS_MEASURE_ID, UOM_DESCR, GL_ACCOUNT_ID, INPUT_ENUM_ID, DETAIL_ENUM_ID, WM_VAL_MOD_ID, STATUS_ENUM_ID, DATA_SOURCE_ID, WM_DATA_SOURCE_ID,
    //
    ORG_UNIT_ROLE_TYPE_ID, ORG_UNIT_ID, IS_POSTED,
    //
    PARTY_ID, ROLE_TYPE_ID, WE_SCORE_CONV_ENUM_ID, WE_ALERT_RULE_ENUM_ID, WE_SCORE_RANGE_ENUM_ID, WE_MEASURE_TYPE_ENUM_ID, WE_WITHOUT_PERF,
    //
    UOM_RANGE_ID, CALC_CUSTOM_METHOD_ID, GL_ACCOUNT_TYPE_DESC, FROM_DATE, THRU_DATE, SEQUENCE_ID, PRODUCT_ID, WE_TRANS_ID, WE_TRANS_ENTRY_ID,
    //
    WE_TRANS_DATE, WE_TRANS_VALUE, WE_TRANS_ACCOUNT_ID, WE_MEASURE_MEASURE_TYPE, WE_TRANS_TYPE_VALUE_ID, WE_TRANS_COMMENTS, WE_TRANS_COMMENTS_LANG, WE_ACCTG_TRANS_ACCOUNT_ID,
    //
    WE_ACCTG_TRANS_ACCOUNT_FIN_ID, WE_TRANS_CURRENCY_UOM_ID, WE_TRANS_COMMENT, WE_TRANS_COMMENT_LANG, ORIG_AMOUNT, TRANS_PRODUCT_ID, WE_TRANS_VALUE_DESC, WE_TRANS_WORK_EFFORT_SNAPSHOT_ID,
    //
    GL_VAL_MOD_ID, CUSTOM_TIME_PERIOD_ID, PERIOD_TYPE_ID, WE_TRANS_PERIOD_IS_CLOSED, WE_TRANS_DECIMAL_SCALE, WE_TRANS_UOM_TYPE, WE_TRANS_UOM_DESC, WE_TRANS_VALUE_CODE,
    //
    WE_TRANS_TYPE_VALUE_DESC, WE_TRANS_WORK_EFFORT_SNAP_SHOT_ID, WE_TRANS_WORK_EFFORT_REVISION_ID, GL_RESOURCE_TYPE_ID, GL_RESOURCE_TYPE_DESC, GL_RESOURCE_TYPE_DESC_LANG, WE_TRANS_ACCOUNT_DESC, WE_TRANS_ACCOUNT_CODE, GROUP_STATUS_ID, 
}
