CREATE VIEW PARTY_HISTORY_VIEW (
    PARTY_ID,
    FROM_DATE,
    THRU_DATE,
    EMPLOYMENT_AMOUNT,
    EMPL_POSITION_TYPE_ID,
    DESCRIPTION,
    COMMENTS
) AS
SELECT
    PH.PARTY_ID,
    PH.FROM_DATE,
    PH.THRU_DATE,
    PH.EMPLOYMENT_AMOUNT,
    PH.EMPL_POSITION_TYPE_ID,
    PH.DESCRIPTION,
    PH.COMMENTS
FROM
    PARTY_HISTORY PH
UNION
SELECT
    PE.PARTY_ID,
    CASE WHEN PE.EMPL_POSITION_TYPE_DATE IS NULL THEN TO_DATE('2000-01-01','YYYY-MM-DD') ELSE PE.EMPL_POSITION_TYPE_DATE END AS FROM_DATE,
    NULL AS THRU_DATE,
    PE.EMPLOYMENT_AMOUNT,
    PE.EMPL_POSITION_TYPE_ID,
    P.DESCRIPTION,
    PE.COMMENTS
FROM 
    PERSON PE
    INNER JOIN PARTY P ON P.PARTY_ID = PE.PARTY_ID