<#include "classpath://sql/FtlQuery-vendor-lib.ftl" />
<#include "classpath://sql/reminder/reminderCommon.sql.ftl" />


<#if retrieveWorkEffortReminder>
<@selectWorkEffortReminderStato />
<#else>
<@selectReminderStato />
</#if>
 
FROM <@table "WORK_EFFORT_TYPE_TYPE"/> RTT
INNER JOIN <@table "WORK_EFFORT_TYPE"/> RWT
        ON RWT.WORK_EFFORT_TYPE_ID = RTT.WORK_EFFORT_TYPE_ID_ROOT
INNER JOIN <@table "WORK_EFFORT_TYPE_STATUS"/> RTS
        ON RTS.WORK_EFFORT_TYPE_ROOT_ID = RTT.WORK_EFFORT_TYPE_ID_ROOT
INNER JOIN <@table "WORK_EFFORT_TYPE"/> WWT
        ON WWT.WORK_EFFORT_TYPE_ID = RTT.WORK_EFFORT_TYPE_ID_TO
INNER JOIN <@table "WORK_EFFORT"/> FIL_W
        ON FIL_W.WORK_EFFORT_TYPE_ID = WWT.WORK_EFFORT_TYPE_ID
       AND FIL_W.CURRENT_STATUS_ID = RTS.CURRENT_STATUS_ID
       AND FIL_W.WORK_EFFORT_REVISION_ID IS NULL
LEFT OUTER JOIN <@table "WORK_EFFORT_PARTY_ASSIGNMENT"/> WAS 
        ON WAS.WORK_EFFORT_ID = FIL_W.WORK_EFFORT_ID
       AND RTS.MANAGEMENT_ROLE_TYPE_ID IS NOT NULL
       AND WAS.ROLE_TYPE_ID = RTS.MANAGEMENT_ROLE_TYPE_ID
INNER JOIN <@table "WORK_EFFORT_TYPE_STATUS"/> WTS
        ON WTS.WORK_EFFORT_TYPE_ROOT_ID = FIL_W.WORK_EFFORT_TYPE_ID
       AND WTS.CURRENT_STATUS_ID = FIL_W.CURRENT_STATUS_ID
INNER JOIN <@table "PARTY"/> WUO
        ON WUO.PARTY_ID = FIL_W.ORG_UNIT_ID
INNER JOIN <@table "PARTY_RELATIONSHIP"/> GR
        ON GR.PARTY_ID_TO = FIL_W.ORG_UNIT_ID
       AND GR.ROLE_TYPE_ID_TO = FIL_W.ORG_UNIT_ROLE_TYPE_ID
       AND GR.PARTY_RELATIONSHIP_TYPE_ID = 'GROUP_ROLLUP'
       AND GR.FROM_DATE <= FIL_W.ESTIMATED_COMPLETION_DATE
       AND (GR.THRU_DATE IS NULL OR GR.THRU_DATE >= FIL_W.ESTIMATED_COMPLETION_DATE)
INNER JOIN <@table "PARTY_RELATIONSHIP"/> VE
        ON VE.PARTY_ID_TO = GR.PARTY_ID_FROM
       AND VE.ROLE_TYPE_ID_TO = GR.ROLE_TYPE_ID_FROM
       AND VE.PARTY_RELATIONSHIP_TYPE_ID = 'GROUP_ROLLUP'
       AND VE.FROM_DATE <= FIL_W.ESTIMATED_COMPLETION_DATE
       AND (VE.THRU_DATE IS NULL OR VE.THRU_DATE >= FIL_W.ESTIMATED_COMPLETION_DATE)
INNER JOIN 
     (SELECT PR.PARTY_ID_TO AS PARTY_ID,
             PR.PARTY_ID_FROM AS ORG_UNIT_ID,
             NULL AS WORK_EFFORT_ID, 
             NULL AS ROLE_TYPE_ID
      FROM <@table "PARTY_RELATIONSHIP"/> PR
      WHERE PR.PARTY_RELATIONSHIP_TYPE_ID = 'ORG_RESPONSIBLE'
        AND PR.THRU_DATE IS NULL
      UNION ALL
      SELECT PA.PARTY_ID AS PARTY_ID,
             NULL AS ORG_UNIT_ID,
             PA.WORK_EFFORT_ID AS WORK_EFFORT_ID,
             PA.ROLE_TYPE_ID AS ROLE_TYPE_ID
      FROM <@table "WORK_EFFORT_PARTY_ASSIGNMENT"/> PA) TY 
        ON ((WTS.MANAG_WE_STATUS_ENUM_ID = 'ORGMANAGER' AND
             TY.ORG_UNIT_ID IS NOT NULL AND TY.ORG_UNIT_ID = FIL_W.ORG_UNIT_ID) OR
            (WTS.MANAG_WE_STATUS_ENUM_ID = 'ROLE' AND
             TY.WORK_EFFORT_ID = FIL_W.WORK_EFFORT_ID AND
             TY.ROLE_TYPE_ID = WTS.MANAGEMENT_ROLE_TYPE_ID) OR
            (WTS.MANAG_WE_STATUS_ENUM_ID = 'SUPMANAGER' AND
             TY.ORG_UNIT_ID IS NOT NULL AND TY.ORG_UNIT_ID = GR.PARTY_ID_FROM) OR
            (WTS.MANAG_WE_STATUS_ENUM_ID = 'TOPMANAGER' AND
             TY.ORG_UNIT_ID IS NOT NULL AND TY.ORG_UNIT_ID = VE.PARTY_ID_FROM))
INNER JOIN <@table "PARTY"/> WRE
        ON WRE.PARTY_ID = TY.PARTY_ID
INNER JOIN <@table "PARTY_CONTACT_MECH"/> PC
        ON PC.PARTY_ID = TY.PARTY_ID
       AND PC.THRU_DATE IS NULL
INNER JOIN <@table "CONTACT_MECH"/> CM
        ON CM.CONTACT_MECH_ID = PC.CONTACT_MECH_ID
       AND CM.CONTACT_MECH_TYPE_ID = 'EMAIL_ADDRESS'
INNER JOIN <@table "WORK_EFFORT_TYPE_PERIOD"/> WTP ON WTP.WORK_EFFORT_TYPE_ID = FIL_W.WORK_EFFORT_TYPE_ID
	   AND WTP.STATUS_ENUM_ID IN ('OPEN', 'REOPEN')
INNER JOIN <@table "CUSTOM_TIME_PERIOD"/> CTP ON WTP.CUSTOM_TIME_PERIOD_ID = CTP.CUSTOM_TIME_PERIOD_ID
       
<#if filterInnerJoin?has_content>        
${filterInnerJoin} 
</#if>

<#if filterLeftJoin?has_content>        
${filterLeftJoin} 
</#if>       
       
WHERE RTT.WORK_EFFORT_TYPE_ID_ROOT = <@param workEffortTypeId />
  AND FIL_W.ESTIMATED_START_DATE <= <@fineAnno "CTP.FROM_DATE"/>
  AND FIL_W.ESTIMATED_COMPLETION_DATE >= <@inizioAnno "CTP.FROM_DATE"/>
  AND FIL_W.SCHEDULED_START_DATE IS NULL
  AND (FIL_W.DATA_SOLL IS NULL OR RTS.FREQ_SOLL IS NULL OR <@param monitoringDate jdbcType.TIMESTAMP /> > <@dateAdd "FIL_W.DATA_SOLL", "RTS.FREQ_SOLL", "day" />)      
  <#if filterWhere?has_content>        
  ${filterWhere} 
  </#if>      
