<#include "classpath://sql/FtlQuery-vendor-lib.ftl" />
<#include "classpath://sql/reminder/reminderCommon.sql.ftl" />

SELECT DISTINCT 
  RWT.ETCH AS SUBJECT,
  <@convertFieldToVarcharMax "RWT.NOTE", "CONTENT" />,
  RWT.ETCH_LANG AS SUBJECT_LANG,
  <@convertFieldToVarcharMax "RWT.NOTE_LANG", "CONTENT_LANG" />,
  WPVA.PARTY_ID AS PARTY_ID,
  CM.CONTACT_MECH_ID AS CONTACT_MECH_ID_TO,
  WPVA.PARTY_ID AS PARTY_ID_TO,
  FIL_W.WORK_EFFORT_ID AS WORK_EFFORT_ID
FROM <@table "WORK_EFFORT_TYPE_TYPE"/> RTT
INNER JOIN <@table "WORK_EFFORT_TYPE"/> RWT
        ON RWT.WORK_EFFORT_TYPE_ID = RTT.WORK_EFFORT_TYPE_ID_ROOT
INNER JOIN <@table "WORK_EFFORT_TYPE_STATUS"/> RTS
        ON RTS.WORK_EFFORT_TYPE_ROOT_ID = RTT.WORK_EFFORT_TYPE_ID_ROOT
INNER JOIN <@table "WORK_EFFORT_TYPE"/> WWT
        ON WWT.WORK_EFFORT_TYPE_ID = RTT.WORK_EFFORT_TYPE_ID_TO
INNER JOIN <@table "WORK_EFFORT"/> FIL_W
        ON FIL_W.WORK_EFFORT_TYPE_ID = WWT.WORK_EFFORT_TYPE_ID
       AND FIL_W.CURRENT_STATUS_ID = RTS.CURRENT_STATUS_ID
       AND FIL_W.WORK_EFFORT_REVISION_ID IS NULL
INNER JOIN <@table "PARTY"/> WUO
        ON WUO.PARTY_ID = FIL_W.ORG_UNIT_ID
INNER JOIN WORK_EFFORT_PARTY_ASSIGNMENT WPVA
     ON (RTS.MANAG_WE_STATUS_ENUM_ID = 'ROLE' AND
             WPVA.WORK_EFFORT_ID = FIL_W.WORK_EFFORT_ID AND
             WPVA.ROLE_TYPE_ID = RTS.MANAGEMENT_ROLE_TYPE_ID)	
INNER JOIN <@table "PARTY_CONTACT_MECH"/> PC ON PC.PARTY_ID = WPVA.PARTY_ID
      AND PC.THRU_DATE IS NULL
INNER JOIN <@table "CONTACT_MECH"/> CM
        ON CM.CONTACT_MECH_ID = PC.CONTACT_MECH_ID
       AND CM.CONTACT_MECH_TYPE_ID = 'EMAIL_ADDRESS'
INNER JOIN <@table "WORK_EFFORT_TYPE_PERIOD"/> WTP ON WTP.WORK_EFFORT_TYPE_ID = FIL_W.WORK_EFFORT_TYPE_ID
	   AND WTP.STATUS_ENUM_ID IN ('OPEN', 'REOPEN')
INNER JOIN <@table "CUSTOM_TIME_PERIOD"/> CTP ON WTP.CUSTOM_TIME_PERIOD_ID = CTP.CUSTOM_TIME_PERIOD_ID

<#if filterInnerJoin?has_content>        
${filterInnerJoin} 
</#if>

<#if filterLeftJoin?has_content>        
${filterLeftJoin} 
</#if>       
       
WHERE RTT.WORK_EFFORT_TYPE_ID_ROOT = <@param workEffortTypeId />
  AND FIL_W.SCHEDULED_START_DATE IS NULL
  AND (FIL_W.DATA_SOLL IS NULL OR RTS.FREQ_SOLL IS NULL OR <@monitoringDateSenzaOra/> > <@dateAddWithoutTime "FIL_W.DATA_SOLL", "RTS.FREQ_SOLL", "day" />)  
  AND WWT.IS_ROOT = 'Y'
  AND FIL_W.ESTIMATED_START_DATE <= <@fineAnno "CTP.FROM_DATE"/>
  AND FIL_W.ESTIMATED_COMPLETION_DATE >= <@inizioAnno "CTP.FROM_DATE"/>
  <#if filterWhere?has_content>        
    ${filterWhere} 
  </#if> 