<#macro selectReminderStato>
SELECT DISTINCT 
  RWT.ETCH AS SUBJECT,
  <@convertFieldToVarcharMax "RWT.NOTE", "CONTENT" />,
  RWT.ETCH_LANG AS SUBJECT_LANG,
  <@convertFieldToVarcharMax "RWT.NOTE_LANG", "CONTENT_LANG" />,
  WAS.PARTY_ID AS EVAL_PARTY_ID,
  WUO.PARTY_ID,
  CM.CONTACT_MECH_ID AS CONTACT_MECH_ID_TO,
  TY.PARTY_ID AS PARTY_ID_TO,
  NULL AS WORK_EFFORT_ID																											
</#macro>

<#macro selectWorkEffortReminderStato>
SELECT DISTINCT 
  RWT.ETCH AS SUBJECT,
  <@convertFieldToVarcharMax "RWT.NOTE", "CONTENT" />,
  RWT.ETCH_LANG AS SUBJECT_LANG,
  <@convertFieldToVarcharMax "RWT.NOTE_LANG", "CONTENT_LANG" />,
  WAS.PARTY_ID AS EVAL_PARTY_ID,
  WUO.PARTY_ID,
  CM.CONTACT_MECH_ID AS CONTACT_MECH_ID_TO,
  TY.PARTY_ID AS PARTY_ID_TO,
  FIL_W.WORK_EFFORT_ID																													
</#macro>


<#macro selectReminder>
SELECT Q.*,
       RWT.NOTE AS CONTENT,
       RWT.ETCH AS SUBJECT,
       RWT.NOTE_LANG AS CONTENT_LANG,
       RWT.ETCH_LANG AS SUBJECT_LANG 
    FROM   (       
                SELECT 
                	   TY.PARTY_ID AS PARTY_ID, -- usato per il report
                	   TY.PARTY_ID AS PARTY_ID_TO, -- usato per scrivere la mail
                	   CM.CONTACT_MECH_ID AS CONTACT_MECH_ID_TO,
                	   RTT.WORK_EFFORT_TYPE_ID_ROOT
       
	    																																	
</#macro>

<#macro selectWorkEffortReminder>
SELECT Q.*,
       RWT.NOTE AS CONTENT,
       RWT.ETCH AS SUBJECT,
       RWT.NOTE_LANG AS CONTENT_LANG,
       RWT.ETCH_LANG AS SUBJECT_LANG 
    FROM   (       
                SELECT 
                	   TY.PARTY_ID AS PARTY_ID, -- usato per il report
                	   TY.PARTY_ID AS PARTY_ID_TO, -- usato per scrivere la mail
                	   CM.CONTACT_MECH_ID AS CONTACT_MECH_ID_TO,
                	   RTT.WORK_EFFORT_TYPE_ID_ROOT, 
			   FIL_W.WORK_EFFORT_ID 
       
	    																																	
</#macro>


<#macro fromReminder>
FROM <@table "WORK_EFFORT_TYPE_TYPE"/> RTT
INNER JOIN <@table "WORK_EFFORT_TYPE_STATUS"/>  RTS ON RTS.WORK_EFFORT_TYPE_ROOT_ID = RTT.WORK_EFFORT_TYPE_ID_ROOT
INNER JOIN <@table "WORK_EFFORT_TYPE"/>  WWT ON WWT.WORK_EFFORT_TYPE_ID = RTT.WORK_EFFORT_TYPE_ID_TO
INNER JOIN <@table "WORK_EFFORT"/>  FIL_W ON FIL_W.WORK_EFFORT_TYPE_ID = WWT.WORK_EFFORT_TYPE_ID
       AND FIL_W.CURRENT_STATUS_ID = RTS.CURRENT_STATUS_ID
       AND FIL_W.WORK_EFFORT_REVISION_ID IS NULL
       <#if organizationId?has_content>
         AND FIL_W.ORGANIZATION_ID = '${organizationId?if_exists}'
       </#if>
INNER JOIN <@table "WORK_EFFORT_TYPE_STATUS"/>  WTS ON WTS.WORK_EFFORT_TYPE_ROOT_ID = FIL_W.WORK_EFFORT_TYPE_ID
       AND WTS.CURRENT_STATUS_ID = FIL_W.CURRENT_STATUS_ID
INNER JOIN <@table "PARTY WUO"/> ON WUO.PARTY_ID = FIL_W.ORG_UNIT_ID
INNER JOIN <@table "PARTY_RELATIONSHIP"/>  GR ON GR.PARTY_ID_TO = FIL_W.ORG_UNIT_ID
       AND GR.ROLE_TYPE_ID_TO = FIL_W.ORG_UNIT_ROLE_TYPE_ID
       AND GR.PARTY_RELATIONSHIP_TYPE_ID = 'GROUP_ROLLUP'
       AND GR.FROM_DATE <= FIL_W.ESTIMATED_COMPLETION_DATE
       AND (GR.THRU_DATE IS NULL OR GR.THRU_DATE >= FIL_W.ESTIMATED_COMPLETION_DATE)
LEFT OUTER JOIN <@table "PARTY_RELATIONSHIP"/> GT ON GT.PARTY_ID_TO = GR.PARTY_ID_FROM
	AND GT.ROLE_TYPE_ID_TO = GR.ROLE_TYPE_ID_FROM
	AND GT.PARTY_RELATIONSHIP_TYPE_ID = 'GROUP_ROLLUP'
	AND GT.FROM_DATE <= FIL_W.ESTIMATED_COMPLETION_DATE
	AND(GT.THRU_DATE IS NULL OR GT.THRU_DATE >= FIL_W.ESTIMATED_COMPLETION_DATE)
INNER JOIN 
     (SELECT PR.PARTY_ID_TO AS PARTY_ID,
     		 PR.PARTY_ID_FROM AS ORG_UNIT_ID,
             NULL AS WORK_EFFORT_ID, 
             NULL AS ROLE_TYPE_ID
      FROM <@table "PARTY_RELATIONSHIP"/> PR
      WHERE PR.PARTY_RELATIONSHIP_TYPE_ID IN ('ORG_RESPONSIBLE', 'ORG_DELEGATE') 
        AND PR.THRU_DATE IS NULL
      UNION ALL
      SELECT PA.PARTY_ID AS PARTY_ID,
      		 NULL AS ORG_UNIT_ID,
             PA.WORK_EFFORT_ID AS WORK_EFFORT_ID, 
             PA.ROLE_TYPE_ID AS ROLE_TYPE_ID
      FROM <@table "WORK_EFFORT_PARTY_ASSIGNMENT"/> PA) TY 
        ON ((WTS.MANAG_WE_STATUS_ENUM_ID = 'ORGMANAGER' AND
             TY.ORG_UNIT_ID = FIL_W.ORG_UNIT_ID) OR
            (WTS.MANAG_WE_STATUS_ENUM_ID = 'ROLE' AND
             TY.WORK_EFFORT_ID = FIL_W.WORK_EFFORT_ID AND
             TY.ROLE_TYPE_ID = WTS.MANAGEMENT_ROLE_TYPE_ID)OR
            (WTS.MANAG_WE_STATUS_ENUM_ID = 'SUPMANAGER' AND
             TY.ORG_UNIT_ID = GR.PARTY_ID_FROM) OR
	    (WTS.MANAG_WE_STATUS_ENUM_ID = 'TOPMANAGER' AND 
	     TY.ORG_UNIT_ID = gt.PARTY_ID_FROM))
INNER JOIN <@table "PARTY"/> WRE ON WRE.PARTY_ID = TY.PARTY_ID
INNER JOIN <@table "PARTY_CONTACT_MECH"/> PC ON PC.PARTY_ID = TY.PARTY_ID
       AND PC.THRU_DATE IS NULL
INNER JOIN <@table "CONTACT_MECH"/> CM ON CM.CONTACT_MECH_ID = PC.CONTACT_MECH_ID
       AND CM.CONTACT_MECH_TYPE_ID = 'EMAIL_ADDRESS'
 
</#macro>


<#macro groupByReminder>
	  GROUP BY
            TY.PARTY_ID,           
            CM.CONTACT_MECH_ID,
            RTT.WORK_EFFORT_TYPE_ID_ROOT ) Q
            
INNER JOIN  <@table "WORK_EFFORT_TYPE"/> RWT ON RWT.WORK_EFFORT_TYPE_ID = Q.WORK_EFFORT_TYPE_ID_ROOT
</#macro>

<#macro groupByWorkEffortReminder>
	  GROUP BY
            TY.PARTY_ID,           
            CM.CONTACT_MECH_ID,
            RTT.WORK_EFFORT_TYPE_ID_ROOT,
	    FIL_W.WORK_EFFORT_ID ) Q
            
INNER JOIN  <@table "WORK_EFFORT_TYPE"/> RWT ON RWT.WORK_EFFORT_TYPE_ID = Q.WORK_EFFORT_TYPE_ID_ROOT
</#macro>